version: '3'
services:
  unifi-network-controller:
    build: .
    container_name: unifi-cotroller
    image: unifi-network-controller
    ports:
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
      - 3478:3478
    volumes:
      - UnifiControllerDataVolume:/var/lib/unifi/db
      - S:/unifi-network-controller/log:/var/log/unifi
      - S:/unifi-network-controller/data/keystore:/var/lib/unifi/keystore
      - S:/unifi-network-controller/data/system.properties:/var/lib/unifi/system.properties
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - IPC_LOCK
    entrypoint: /run.sh

volumes:
  UnifiControllerDataVolume:
